### ISSUE TITLE
PCB

### ISSUE THREAD

**Issue by curlyz** [KitSprout/UWB-Node#1]
Hi Hom
I think your adapter board is very interesting , but follow Decawave document stated that you shouldnt put anything beneath DWM1000 antenna?
And have you got some progress yet :) 
Looking foward for your answer

**Comment by hom-wang** [comment]
Hi curlyz,

The image shown below is from
`ProductBrief_dwm1000-datasheet-v1.4 - 5.1 Application Board Layout Guidelines`

![image](https://cloud.githubusercontent.com/assets/4789358/20621422/66218a78-b339-11e6-9b84-628b30f1961a.png)

There are two way to place the module with antenna, just follow no metal either side, above or below is fine.

Hope it helps : )

**Comment by curlyz** [comment]
I see you have made tons of code, >20mb of code, really??
btw , have you make any ranging work yet Hom?

**Comment by hom-wang** [comment]
just some example about peripheral.
yes, but that is my master's thesis, not inconvenient to open now.
