### ISSUE TITLE
STM32 SWD connector compatibility with STLINK interfaces

### ISSUE THREAD

**Issue by alberto-fc** [KitSprout/UWB-Node#6]
Hi,

First and foremost: Thank you, for sharing your work and making such an effort to keep the things tight and tidy.

My question is about the P1 connector in this design (SWD and UART for the STM32) and how you are using it.

I just checked with the current (and last) STLINK-V3 and I can't see a way to make a direct connection from the STLINK header to this design without an adapter board.

So I'm just checking if you're using a custom design for debugging part with your own pinout or I'm missing something.

Grateful for your time, best regards,
A.

**Comment by hom-wang** [comment]
Hi,
P1 connector pin order designed by my self, 1.27mm header. You need to make a adapter board to connect.
